# Copyright IBM Corp. 2026
# SPDX-License-Identifier: MPL-2.0

apiVersion: v2
name: boundary-controller
description: Official HashiCorp Boundary Controller Chart
type: application
version: 0.1.0-beta
appVersion: "0.21-ent"
kubeVersion: ">= 1.34.0-0"
keywords:
  - boundary
  - hashicorp
  - identity
  - access-control
  - security
  - zero-trust
  - privileged-access-management
  - pam
  - proxy
home: https://www.boundaryproject.io/
icon: https://raw.githubusercontent.com/hashicorp/boundary/main/boundary.png
sources:
  - https://github.com/hashicorp/boundary
  - https://github.com/hashicorp/boundary-controller-helm
maintainers:
  - name: HashiCorp
  