apiVersion: v1
kind: Service
metadata:
  name: {{ include "boundary.controller.serviceName" . }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.controller.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.type }}
  ports:
    - port: {{ .Values.controller.service.port }}
      targetPort: {{ .Values.controller.service.targetPort }}
      protocol: TCP
      name: api
  selector:
    {{- include "boundary.controller.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "boundary.controller.clusterServiceName" . }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: {{ .Values.controller.service.clusterType }}
  ports:
    - port: {{ .Values.controller.service.clusterPort }}
      targetPort: {{ .Values.controller.service.clusterTargetPort }}
      protocol: TCP
      name: cluster
    - port: {{ .Values.controller.service.opsPort }}
      targetPort: {{ .Values.controller.service.opsTargetPort }}
      protocol: TCP
      name: ops
  selector:
    {{- include "boundary.controller.selectorLabels" . | nindent 4 }}
