# Copyright IBM Corp. 2026

apiVersion: v1
kind: Service
metadata:
  name: {{ include "boundary.controller.apiServiceName" . }}
  namespace: {{ include "boundary.namespace" . }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.controller.service.api.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.api.type }}
  ports:
    - port: {{ .Values.controller.service.api.port }}
      targetPort: {{ .Values.controller.service.api.targetPort }}
      protocol: TCP
      name: api
  selector:
    {{- include "boundary.controller.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "boundary.controller.clusterServiceName" . }}
  namespace: {{ include "boundary.namespace" . }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.controller.service.cluster.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.cluster.type }}
  ports:
    - port: {{ .Values.controller.service.cluster.port }}
      targetPort: {{ .Values.controller.service.cluster.targetPort }}
      protocol: TCP
      name: cluster
  selector:
    {{- include "boundary.controller.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "boundary.controller.opsServiceName" . }}
  namespace: {{ include "boundary.namespace" . }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  {{- with .Values.controller.service.ops.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.controller.service.ops.type }}
  ports:
    - port: {{ .Values.controller.service.ops.port }}
      targetPort: {{ .Values.controller.service.ops.targetPort }}
      protocol: TCP
      name: ops
  selector:
    {{- include "boundary.controller.selectorLabels" . | nindent 4 }}
